searches:
  - name: Armoire Laval
    url: "https://www.leboncoin.fr/recherche?category=19&locations=Laval_53000__48.07268_-0.77307_5000_20000&price=min-250&furniture_type=armoire,dressingetpenderie"
