name: Leboncoin Alert Cron

on:
  schedule:
    - cron: "0 6 * * *"  # tous les jours à 6h UTC
  workflow_dispatch:     # lancement manuel possible

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: TEST

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python main.py
